export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_SUCCEEDED = "LOGOUT_SUCCEEDED";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_LOADING = "LOGOUT_LOADING";

export const PROFILE_REQUESTED = "PROFILE_REQUESTED";
export const PROFILE_SUCCEEDED = "PROFILE_SUCCEEDED";
export const PROFILE_FAILED = "PROFILE_FAILED";
export const PROFILE_LOADING = "PROFILE_LOADING";

export const CHECK_LOGIN = "CHECK_LOGIN";
export const CHECK_LOGIN_PENDING = "CHECK_LOGIN_PENDING";
export const CHECK_LOGIN_FALSE = "CHECK_LOGIN_FALSE";
export const CHECK_LOGIN_TRUE = "CHECK_LOGIN_TRUE";

export const REGISTER_REQUESTED = "REGISTER_REQUESTED";
export const REGISTER_SUCCEEDED = "REGISTER_SUCCEEDED";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_LOADING = "REGISTER_LOADING";

export const SPEND_CATEGORIES_REQUESTED = "SPEND_CATEGORIES_REQUESTED";
export const SPEND_CATEGORIES_SUCCESS = "SPEND_CATEGORIES_SUCCESS";
export const SPEND_CATEGORIES_FAILED = "SPEND_CATEGORIES_FAILED";

export const INCOME_CATEGORIES_REQUESTED = "INCOME_CATEGORIES_REQUESTED";
export const INCOME_CATEGORIES_SUCCESS = "INCOME_CATEGORIES_SUCCESS";
export const INCOME_CATEGORIES_FAILED = "INCOME_CATEGORIES_FAILED";

export const ACCOUNTS_REQUESTED = "ACCOUNTS_REQUESTED";
export const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS";
export const ACCOUNTS_FAILED = "ACCOUNTS_FAILED";
export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";

export const SPEND_REQUESTED = "SPEND_REQUESTED";
export const SPEND_SUCCEEDED = "SPEND_SUCCEEDED";
export const SPEND_FAILED = "SPEND_FAILED";
export const SPEND_LOADING = "SPEND_LOADING";

export const INCOME_REQUESTED = "INCOME_REQUESTED";
export const INCOME_SUCCEEDED = "INCOME_SUCCEEDED";
export const INCOME_FAILED = "INCOME_FAILED";
export const INCOME_LOADING = "INCOME_LOADING";

export const OP_HISTORY_REQUESTED = "OP_HISTORY_REQUESTED";
export const OP_HISTORY_SUCCEEDED = "OP_HISTORY_SUCCEEDED";
export const OP_HISTORY_FAILED = "OP_HISTORY_FAILED";
export const OP_HISTORY_LOADING = "OP_HISTORY_LOADING";

export const SET_AVATAR_REQUESTED = "SET_AVATAR_REQUESTED";
export const SET_AVATAR_SUCCEEDED = "SET_AVATAR_SUCCEEDED";
export const SET_AVATAR_FAILED = "SET_AVATAR_FAILED";

export const DEL_ACCOUNT_REQUESTED = "DEL_ACCOUNT_REQUESTED";
export const DEL_ACCOUNT_SUCCEEDED = "DEL_ACCOUNT_SUCCEEDED";
export const DEL_ACCOUNT_FAILED = "DEL_ACCOUNT_FAILED";

export const CREATE_FAMILY_LOADING = "CREATE_FAMILY_LOADING";
export const CREATE_FAMILY_REQUESTED = "CREATE_FAMILY_REQUESTED";
export const CREATE_FAMILY_SUCCEEDED = "CREATE_FAMILY_SUCCEEDED";
export const CREATE_FAMILY_FAILED = "CREATE_FAMILY_FAILED";

export const GET_FAMILIES_LOADING = "GET_FAMILIES_LOADING";
export const GET_FAMILIES_REQUESTED = "GET_FAMILIES_REQUESTED";
export const GET_FAMILIES_SUCCEEDED = "GET_FAMILIES_SUCCEEDED";
export const GET_FAMILIES_FAILED = "GET_FAMILIES_FAILED";

export const SET_FAMILY_LOADING = "SET_FAMILY_LOADING";
export const SET_FAMILY_REQUESTED = "SET_FAMILY_REQUESTED";
export const SET_FAMILY_SUCCEEDED = "SET_FAMILY_SUCCEEDED";
export const SET_FAMILY_FAILED = "SET_FAMILY_FAILED";

export const GET_CURRENCIES_LOADING = "GET_CURRENCIES_LOADING";
export const GET_CURRENCIES_REQUESTED = "GET_CURRENCIES_REQUESTED";
export const GET_CURRENCIES_SUCCEEDED = "GET_CURRENCIES_SUCCEEDED";
export const GET_CURRENCIES_FAILED = "GET_CURRENCIES_FAILED";

export const GET_ACCOUNT_TYPES_LOADING = "GET_ACCOUNT_TYPES_LOADING";
export const GET_ACCOUNT_TYPES_REQUESTED = "GET_ACCOUNT_TYPES_REQUESTED";
export const GET_ACCOUNT_TYPES_SUCCEEDED = "GET_ACCOUNT_TYPES_SUCCEEDED";
export const GET_ACCOUNT_TYPES_FAILED = "GET_ACCOUNT_TYPES_FAILED";

export const ADD_ACCOUNT_LOADING = "ADD_ACCOUNT_LOADING";
export const ADD_ACCOUNT_REQUESTED = "ADD_ACCOUNT_REQUESTED";
export const ADD_ACCOUNT_SUCCEEDED = "ADD_ACCOUNT_SUCCEEDED";
export const ADD_ACCOUNT_FAILED = "ADD_ACCOUNT_FAILED";

export const GET_INCOME_BY_DATE_LOADING = "GET_INCOME_BY_DATE_LOADING";
export const GET_INCOME_BY_DATE_REQUESTED = "GET_INCOME_BY_DATE_REQUESTED";
export const GET_INCOME_BY_DATE_SUCCEEDED = "GET_INCOME_BY_DATE_SUCCEEDED";
export const GET_INCOME_BY_DATE_FAILED = "GET_INCOME_BY_DATE_FAILED";

export const GET_SPEND_BY_DATE_LOADING = "GET_SPEND_BY_DATE_LOADING";
export const GET_SPEND_BY_DATE_REQUESTED = "GET_SPEND_BY_DATE_REQUESTED";
export const GET_SPEND_BY_DATE_SUCCEEDED = "GET_SPEND_BY_DATE_SUCCEEDED";
export const GET_SPEND_BY_DATE_FAILED = "GET_SPEND_BY_DATE_FAILED";

export const GET_INCOME_BY_FAM_DATE_LOADING = "GET_INCOME_BY_FAM_DATE_LOADING";
export const GET_INCOME_BY_FAM_DATE_REQUESTED =
  "GET_INCOME_BY_FAM_DATE_REQUESTED";
export const GET_INCOME_BY_FAM_DATE_SUCCEEDED =
  "GET_INCOME_BY_FAM_DATE_SUCCEEDED";
export const GET_INCOME_BY_FAM_DATE_FAILED = "GET_INCOME_BY_FAM_DATE_FAILED";

export const GET_SPEND_BY_FAM_DATE_LOADING = "GET_SPEND_BY_FAM_DATE_LOADING";
export const GET_SPEND_BY_FAM_DATE_REQUESTED =
  "GET_SPEND_BY_FAM_DATE_REQUESTED";
export const GET_SPEND_BY_FAM_DATE_SUCCEEDED =
  "GET_SPEND_BY_FAM_DATE_SUCCEEDED";
export const GET_SPEND_BY_FAM_DATE_FAILED = "GET_SPEND_BY_FAM_DATE_FAILED";

export const GET_CATEGORY_REPORT_LOADING = "GET_CATEGORY_REPORT_LOADING";
export const GET_CATEGORY_REPORT_REQUESTED = "GET_CATEGORY_REPORT_REQUESTED";
export const GET_CATEGORY_REPORT_SUCCEEDED = "GET_CATEGORY_REPORT_SUCCEEDED";
export const GET_CATEGORY_REPORT_FAILED = "GET_CATEGORY_REPORT_FAILED";

export const SET_DATE = "SET_DATE";
export const SET_DATE_FAIL = "SET_DATE_FAILED";

export const ADD_SPEND_CATEGORY_LOADING = "ADD_SPEND_CATEGORY_LOADING";
export const ADD_SPEND_CATEGORY_REQUESTED = "ADD_SPEND_CATEGORY_REQUESTED";
export const ADD_SPEND_CATEGORY_SUCCEEDED = "ADD_SPEND_CATEGORY_SUCCEEDED";
export const ADD_SPEND_CATEGORY_FAILED = "ADD_SPEND_CATEGORY_FAILED";

export const ADD_INCOME_CATEGORY_LOADING = "ADD_INCOME_CATEGORY_LOADING";
export const ADD_INCOME_CATEGORY_REQUESTED = "ADD_INCOME_CATEGORY_REQUESTED";
export const ADD_INCOME_CATEGORY_SUCCEEDED = "ADD_INCOME_CATEGORY_SUCCEEDED";
export const ADD_INCOME_CATEGORY_FAILED = "ADD_INCOME_CATEGORY_FAILED";
