import { all, fork } from "redux-saga/effects";
import {
  watchGetProfile,
  watchLogout,
  watchLogin,
  watchCheckLogin,
  watchRegister,
  watchGetSpendCategories,
  watchGetAccountById,
  watchSetSpend,
  watchGetIncomeCategories,
  watchSetIncome,
  watchGetOpHistory,
  watchSetAvatar,
  watchDelAccount,
  watchCreateFamily,
  watchGetFamilies,
  watchSetFamily,
  watchGetAccountTypes,
  watchGetCurrencies,
  watchAddAccount,
  watchGetSpendByDate,
  watchGetIncomeByDate,
  watchGetIncomeByFamDate,
  watchGetSpendByFamDate,
  watchGetCategoryReport,
  watchAddIncomeCategory,
  watchAddSpendCategory
} from "./access-sagas";

export default function* rootSaga() {
  yield all([
    fork(watchGetProfile),
    fork(watchLogin),
    fork(watchLogout),
    fork(watchCheckLogin),
    fork(watchRegister),
    fork(watchGetSpendCategories),
    fork(watchGetAccountById),
    fork(watchSetSpend),
    fork(watchGetIncomeCategories),
    fork(watchSetIncome),
    fork(watchGetOpHistory),
    fork(watchSetAvatar),
    fork(watchDelAccount),
    fork(watchCreateFamily),
    fork(watchGetFamilies),
    fork(watchSetFamily),
    fork(watchGetAccountTypes),
    fork(watchGetCurrencies),
    fork(watchAddAccount),
    fork(watchGetSpendByDate),
    fork(watchGetIncomeByDate),
    fork(watchGetIncomeByFamDate),
    fork(watchGetSpendByFamDate),
    fork(watchGetCategoryReport),
    fork(watchAddIncomeCategory),
    fork(watchAddSpendCategory)
  ]);
}
